name: Generate Pacman Graph

on:
  workflow_dispatch:

jobs:
  generate:
    runs-on: ubuntu-latest

    steps:
      - name: generate pacman
        uses: Platane/snk@v3
        with:
          github_user_name: diogobennertz
          github_token: ${{ secrets.GH_PAT }}
          outputs: |
            dist/pacman-contribution-graph.svg

      - name: push pacman
        uses: crazy-max/ghaction-github-pages@v3
        with:
          github_token: ${{ secrets.GH_PAT }}
          target_branch: output
          build_dir: dist
